### ISSUE TITLE
падение .net framework

### ISSUE THREAD

**Issue by Makishima** [BladeMight/Mahou#125]
Перед вылетом залип, то ли shift, то ли caps lock

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Locale string [Switch between layouts] does not contain a layout uID.
   at Mahou.Locales.GetLocaleFromString(String localeString)
   at Mahou.KMHook.<>c__DisplayClass1c.<SpecificKey>b__1b()
   at Mahou.KMHook.DoSelf(Action self_action)
   at Mahou.KMHook.SpecificKey(Keys Key, UInt32 MSG, Int32 specificKey, Int32 specKeyId)
   at Mahou.KMHook.ListenKeyboard(Int32 vkCode, UInt32 MSG, Int16 Flags)
   at Mahou.RawInputForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Mahou
    Assembly Version: 2.4.0.8
    Win32 Version: 2.4.0.8
    CodeBase: file:///D:/downloads/Mahou/Mahou.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2104.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2103.2 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Comment by Makishima** [comment]
[2017.08.21.txt](https://github.com/BladeMight/Mahou/files/1238560/2017.08.21.txt)

**Comment by BladeMight** [comment]
@Makishima Mahou не смог получить раскладку из выбранных во вкладке Раскладки при нажатии на назначенную у тебя клавишу в секции "менять раскладку 1 клавишей", пересмотри настройки вдруг там пусто.

**Comment by BladeMight** [comment]
А произошло все из-за того что [Switch between layouts] не равна в [Переключать между раскладками], после переключения языка интерфейса, исправил в https://github.com/BladeMight/Mahou/commit/0ac4e4ad3229b7a85f058a6a977a047062073b43

**Comment by BladeMight** [comment]
@Makishima Релиз [Mahou-v2.4.5.0](https://github.com/BladeMight/Mahou/releases/tag/v2.4.5.0).
